# Linear Algebra

In [31]:
import numpy as np 

## Matrix 

In [32]:
A=np.array([[2, -1], [0, 3]])
B=np.array([[1, 2], [-3, 4]])

sum=A+B
dot_product=A@B
expr=3*A - 2*B
print("Sum:\n", sum)
print("Dot_Product:\n", dot_product)
print("Expression 3A - 2B:\n", expr)

Sum:
 [[ 3  1]
 [-3  7]]
Dot_Product:
 [[ 5  0]
 [-9 12]]
Expression 3A - 2B:
 [[ 4 -7]
 [ 6  1]]


### Matrix Operations such as Addition, Dot Product, and normal expression of matrix are evaluated. 

# 2. Determinants and Inverses  


In [33]:
# Find the determinant of A.
# Determine whether A is invertible. If yes, calculate A−1.
det_A=np.linalg.det(A)
if det_A != 0:
    inv_A=np.linalg.inv(A)
    print("Determinant of A:", det_A)
    print("Inverse of A:\n", inv_A)
    
else:
    print("Matrix A is not invertible.")    

Determinant of A: 6.0
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


### Performing matrix inversion and determinant of A matrix 


# 3. Eigenvalues and Eigenvectors  

In [34]:
# Compute the eigenvalues and eigenvectors of the matrix:
# C=[[4    1], [​−2       1]​]

C=np.array([[4, 1], [-2, 1]])
eigenvalues, eigenvectors=np.linalg.eig(C)
print("Eigenvalues of C:", eigenvalues)
print("Eigenvectors of C:\n", eigenvectors)

Eigenvalues of C: [3. 2.]
Eigenvectors of C:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


### Calculating Eigenvalues and Eigenvectors 

# 4. Price Prediction 


In [35]:
# You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
# car 1:
# x1: 4
# x2:  1.5
# x3: 100
# and price: 20

# car 2:
# x1: 6
# x2:  2.0
# x3: 150
# and price: 30

# Then, find the price of a car 3 with features
# x1: 8
# x2:  3.0
# x3: 200
# price:?


X = np.array([
    [1, 4, 1.5, 100],
    [1, 6, 2.0, 150]
])


y = np.array([20, 30])


beta = np.linalg.pinv(X) @ y

print("Coefficients (beta):")
print(beta)



Coefficients (beta):
[-0.00079866  0.00798658  0.00159732  0.19966456]


# Prediction Price For Car 

In [36]:
x3 = np.array([1, 8, 3.0, 200])

price_pred = x3 @ beta
price_pred

np.float64(40.00079865825414)